import type { Project, Task, TimeEntry, CalendarEvent, Client, Invoice, Stats, User } from '@/types';

export const currentUser: User = {
  id: 'user-1',
  name: 'Alex Morgan',
  email: 'alex@freelanceos.com',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
  role: 'Freelance Developer',
  timezone: 'America/New_York',
  hourlyRate: 125,
};

export const stats: Stats = {
  totalRevenue: 84250,
  pendingPayments: 12500,
  activeProjects: 6,
  completedTasks: 47,
  hoursThisWeek: 38.5,
  hoursThisMonth: 142,
};

export const projects: Project[] = [
  {
    id: 'proj-1',
    name: 'E-commerce Platform',
    client: 'TechCorp Inc.',
    status: 'active',
    progress: 65,
    budget: 25000,
    spent: 16250,
    deadline: '2024-03-15',
    description: 'Full-stack e-commerce solution with payment integration',
    color: '#3B82F6',
  },
  {
    id: 'proj-2',
    name: 'Mobile App Redesign',
    client: 'StartupXYZ',
    status: 'active',
    progress: 40,
    budget: 18000,
    spent: 7200,
    deadline: '2024-04-01',
    description: 'Complete UI/UX overhaul for iOS and Android app',
    color: '#10B981',
  },
  {
    id: 'proj-3',
    name: 'Dashboard Analytics',
    client: 'DataFlow Ltd.',
    status: 'active',
    progress: 85,
    budget: 12000,
    spent: 10200,
    deadline: '2024-02-28',
    description: 'Real-time analytics dashboard with custom visualizations',
    color: '#F59E0B',
  },
  {
    id: 'proj-4',
    name: 'API Integration',
    client: 'CloudServe',
    status: 'on-hold',
    progress: 30,
    budget: 8000,
    spent: 2400,
    deadline: '2024-05-10',
    description: 'Third-party API integrations and middleware development',
    color: '#8B5CF6',
  },
  {
    id: 'proj-5',
    name: 'Brand Website',
    client: 'Creative Agency',
    status: 'completed',
    progress: 100,
    budget: 15000,
    spent: 14500,
    deadline: '2024-01-20',
    description: 'Corporate website with CMS integration',
    color: '#EC4899',
  },
  {
    id: 'proj-6',
    name: 'SaaS Platform',
    client: 'InnovateTech',
    status: 'active',
    progress: 20,
    budget: 45000,
    spent: 9000,
    deadline: '2024-06-30',
    description: 'Multi-tenant SaaS application with subscription billing',
    color: '#06B6D4',
  },
];

export const tasks: Task[] = [
  {
    id: 'task-1',
    title: 'Implement payment gateway',
    description: 'Integrate Stripe payment processing with checkout flow',
    projectId: 'proj-1',
    projectName: 'E-commerce Platform',
    status: 'in-progress',
    priority: 'high',
    dueDate: '2024-02-20',
    assignee: 'Alex Morgan',
    timeEstimate: 16,
    timeSpent: 8,
  },
  {
    id: 'task-2',
    title: 'Design product catalog UI',
    description: 'Create responsive product grid with filtering options',
    projectId: 'proj-1',
    projectName: 'E-commerce Platform',
    status: 'completed',
    priority: 'medium',
    dueDate: '2024-02-15',
    assignee: 'Alex Morgan',
    timeEstimate: 12,
    timeSpent: 10,
  },
  {
    id: 'task-3',
    title: 'User onboarding flow',
    description: 'Design and implement new user onboarding screens',
    projectId: 'proj-2',
    projectName: 'Mobile App Redesign',
    status: 'todo',
    priority: 'urgent',
    dueDate: '2024-02-25',
    assignee: 'Alex Morgan',
    timeEstimate: 20,
    timeSpent: 0,
  },
  {
    id: 'task-4',
    title: 'Real-time data visualization',
    description: 'Implement WebSocket connection for live chart updates',
    projectId: 'proj-3',
    projectName: 'Dashboard Analytics',
    status: 'review',
    priority: 'high',
    dueDate: '2024-02-22',
    assignee: 'Alex Morgan',
    timeEstimate: 24,
    timeSpent: 20,
  },
  {
    id: 'task-5',
    title: 'API documentation',
    description: 'Write comprehensive API docs with examples',
    projectId: 'proj-4',
    projectName: 'API Integration',
    status: 'todo',
    priority: 'low',
    dueDate: '2024-03-01',
    assignee: 'Alex Morgan',
    timeEstimate: 8,
    timeSpent: 0,
  },
  {
    id: 'task-6',
    title: 'Performance optimization',
    description: 'Optimize database queries and implement caching',
    projectId: 'proj-6',
    projectName: 'SaaS Platform',
    status: 'in-progress',
    priority: 'medium',
    dueDate: '2024-02-28',
    assignee: 'Alex Morgan',
    timeEstimate: 16,
    timeSpent: 6,
  },
  {
    id: 'task-7',
    title: 'Unit test coverage',
    description: 'Increase test coverage to 80% for core modules',
    projectId: 'proj-1',
    projectName: 'E-commerce Platform',
    status: 'todo',
    priority: 'medium',
    dueDate: '2024-03-05',
    assignee: 'Alex Morgan',
    timeEstimate: 12,
    timeSpent: 0,
  },
  {
    id: 'task-8',
    title: 'Mobile responsiveness',
    description: 'Fix layout issues on tablet and mobile devices',
    projectId: 'proj-3',
    projectName: 'Dashboard Analytics',
    status: 'completed',
    priority: 'high',
    dueDate: '2024-02-18',
    assignee: 'Alex Morgan',
    timeEstimate: 6,
    timeSpent: 5,
  },
];

export const timeEntries: TimeEntry[] = [
  {
    id: 'time-1',
    projectId: 'proj-1',
    projectName: 'E-commerce Platform',
    taskId: 'task-1',
    taskName: 'Implement payment gateway',
    description: 'Working on Stripe integration',
    startTime: '2024-02-19T09:00:00',
    endTime: '2024-02-19T12:30:00',
    duration: 3.5,
    billable: true,
    rate: 125,
  },
  {
    id: 'time-2',
    projectId: 'proj-3',
    projectName: 'Dashboard Analytics',
    taskId: 'task-4',
    taskName: 'Real-time data visualization',
    description: 'WebSocket implementation',
    startTime: '2024-02-19T13:30:00',
    endTime: '2024-02-19T17:00:00',
    duration: 3.5,
    billable: true,
    rate: 125,
  },
  {
    id: 'time-3',
    projectId: 'proj-2',
    projectName: 'Mobile App Redesign',
    taskId: 'task-3',
    taskName: 'User onboarding flow',
    description: 'Wireframing onboarding screens',
    startTime: '2024-02-18T10:00:00',
    endTime: '2024-02-18T14:00:00',
    duration: 4,
    billable: true,
    rate: 125,
  },
  {
    id: 'time-4',
    projectId: 'proj-6',
    projectName: 'SaaS Platform',
    taskId: 'task-6',
    taskName: 'Performance optimization',
    description: 'Database query optimization',
    startTime: '2024-02-18T15:00:00',
    endTime: '2024-02-18T18:00:00',
    duration: 3,
    billable: true,
    rate: 125,
  },
];

export const calendarEvents: CalendarEvent[] = [
  {
    id: 'event-1',
    title: 'Client Call - TechCorp',
    description: 'Weekly progress update meeting',
    startDate: '2024-02-20T10:00:00',
    endDate: '2024-02-20T11:00:00',
    type: 'meeting',
    projectId: 'proj-1',
    color: '#3B82F6',
  },
  {
    id: 'event-2',
    title: 'Dashboard Deadline',
    description: 'Final delivery for analytics dashboard',
    startDate: '2024-02-28T17:00:00',
    endDate: '2024-02-28T17:00:00',
    type: 'deadline',
    projectId: 'proj-3',
    color: '#EF4444',
  },
  {
    id: 'event-3',
    title: 'Design Review',
    description: 'Review mobile app mockups with client',
    startDate: '2024-02-22T14:00:00',
    endDate: '2024-02-22T15:30:00',
    type: 'meeting',
    projectId: 'proj-2',
    color: '#10B981',
  },
  {
    id: 'event-4',
    title: 'Invoice Due',
    description: 'Send invoice for completed website project',
    startDate: '2024-02-25T09:00:00',
    endDate: '2024-02-25T09:00:00',
    type: 'reminder',
    color: '#F59E0B',
  },
  {
    id: 'event-5',
    title: 'Code Review Session',
    description: 'Review payment integration code',
    startDate: '2024-02-21T11:00:00',
    endDate: '2024-02-21T12:00:00',
    type: 'task',
    projectId: 'proj-1',
    color: '#8B5CF6',
  },
];

export const clients: Client[] = [
  {
    id: 'client-1',
    name: 'John Smith',
    email: 'john@techcorp.com',
    company: 'TechCorp Inc.',
    phone: '+1 (555) 123-4567',
  },
  {
    id: 'client-2',
    name: 'Sarah Johnson',
    email: 'sarah@startupxyz.io',
    company: 'StartupXYZ',
    phone: '+1 (555) 234-5678',
  },
  {
    id: 'client-3',
    name: 'Michael Chen',
    email: 'michael@dataflow.com',
    company: 'DataFlow Ltd.',
    phone: '+1 (555) 345-6789',
  },
  {
    id: 'client-4',
    name: 'Emily Davis',
    email: 'emily@cloudserve.io',
    company: 'CloudServe',
    phone: '+1 (555) 456-7890',
  },
];

export const invoices: Invoice[] = [
  {
    id: 'inv-1',
    clientId: 'client-1',
    clientName: 'TechCorp Inc.',
    projectId: 'proj-1',
    projectName: 'E-commerce Platform',
    amount: 8500,
    status: 'paid',
    dueDate: '2024-02-01',
    createdAt: '2024-01-15',
  },
  {
    id: 'inv-2',
    clientId: 'client-3',
    clientName: 'DataFlow Ltd.',
    projectId: 'proj-3',
    projectName: 'Dashboard Analytics',
    amount: 5000,
    status: 'sent',
    dueDate: '2024-02-28',
    createdAt: '2024-02-10',
  },
  {
    id: 'inv-3',
    clientId: 'client-2',
    clientName: 'StartupXYZ',
    projectId: 'proj-2',
    projectName: 'Mobile App Redesign',
    amount: 7500,
    status: 'overdue',
    dueDate: '2024-02-10',
    createdAt: '2024-01-25',
  },
];

export const revenueData = [
  { month: 'Jan', revenue: 12500, hours: 98 },
  { month: 'Feb', revenue: 15200, hours: 122 },
  { month: 'Mar', revenue: 18400, hours: 147 },
  { month: 'Apr', revenue: 14800, hours: 118 },
  { month: 'May', revenue: 21000, hours: 168 },
  { month: 'Jun', revenue: 19500, hours: 156 },
];

export const projectDistribution = [
  { name: 'E-commerce', value: 35, color: '#3B82F6' },
  { name: 'Mobile Apps', value: 25, color: '#10B981' },
  { name: 'Analytics', value: 20, color: '#F59E0B' },
  { name: 'API Work', value: 12, color: '#8B5CF6' },
  { name: 'Other', value: 8, color: '#EC4899' },
];
